AllCops:
  TargetRubyVersion: 2.2
Style/FileName: # Use snake_case for source file names
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
ClassLength:
  Max: 150
Style/Semicolon:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Documentation:
  Enabled: false
