Metrics/PerceivedComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
ClassLength:
  Max: 150
Style/Semicolon:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Documentation:
  Enabled: false
