source 'https://rubygems.org'
# source 'http://ruby.taobao.org/'

gem 'activesupport'
gem 'sinatra', '~> 1.4'
gem 'puma'
gem 'i18n'
gem 'sinatra-contrib'
gem 'sinatra-flash'
gem 'sinatra-redirect-with-flash'
gem 'slim'
gem 'http_accept_language'

group :development do
  gem 'rake'
  gem 'rspec'
  gem 'pry-byebug'
  gem 'awesome_print'
  gem 'simplecov'
  gem 'guard-rspec'
  gem 'guard-rubocop'
  gem 'guard-ctags-bundler'
  gem 'mdoc'
  gem 'guard-rake'
  gem 'iye'
  gem 'google-translate'
  gem 'guard-cucumber'
  gem 'cucumber'
  gem 'capybara'
  gem 'poltergeist'
  gem 'selenium-webdriver'
  gem 'git'
  gem 'diffy'
  gem 'fastimage'
  gem 'sass'
  gem 'uglifier'
end
