source "https://rubygems.org"
# source 'http://ruby.taobao.org/'

gem "activesupport"
gem "sinatra", "~> 1.4"
gem "puma"
gem "sinatra-contrib"
gem "sinatra-flash"
gem "sinatra-redirect-with-flash"
gem "slim"
gem "i18n"
gem "http_accept_language"

group :development do
  gem "rake"
  gem "rspec"
  gem "pry-byebug"
  gem "awesome_print"
  gem "simplecov"
  gem "guard-rspec"
  gem "guard-rubocop"
  gem "mdoc"
  gem "guard-rake"
  gem "rack-test"
  gem "guard-cucumber"
  gem "cucumber"
  gem "capybara"
  gem "poltergeist"
  gem "selenium-webdriver"
end
