---
:production:
  :img_dir: app/assets/img
  :img_url_prefix: "/img"
  :files:
    application.css:
    - http://assets.vikkr.com/application.dav88.css
    application.js:
    - http://assets.vikkr.com/application.davay.js
:local_assets:
  :img_dir: app/assets/img
  :img_url_prefix: "/img"
  :files:
    application.css:
    - "/assets/app/assets/min/application.dav88.css"
    application.js:
    - "/assets/app/assets/min/application.davay.js"
:development:
  :img_dir: app/assets/img
  :img_url_prefix: "/img"
  :files:
    application.css:
    - "/assets/app/assets/css/standard.css"
    - "/assets/app/assets/css/edit.css"
    application.js:
    - "/assets/app/assets/js/base.js"
    - "/assets/app/assets/js/extra.js"
